"""Created file_records table

Revision ID: 28b51ff49007
Revises: 
Create Date: 2025-11-04 19:33:28.154365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b51ff49007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_filename'), 'file_records', ['filename'], unique=True)
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.create_index(op.f('ix_file_records_status'), 'file_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_records_status'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_index(op.f('ix_file_records_filename'), table_name='file_records')
    op.drop_table('file_records')
    # ### end Alembic commands ###
