"""added eta_seconds column in jobs

Revision ID: 47bbb413829a
Revises: 75ec22e01765
Create Date: 2025-11-06 16:52:23.451912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bbb413829a'
down_revision: Union[str, Sequence[str], None] = '75ec22e01765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('eta_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'eta_seconds')
    # ### end Alembic commands ###
